### ISSUE TITLE
'reduce' is not defined

### ISSUE THREAD

**Issue by colinmford** [roboDocs/ScaleFast#2]
I am getting this traceback when I try to use more than 2 masters at a time.

```Traceback (most recent call last):
  File "lib/doodleDelegate.pyc", line 97, in sendEvent_
  File "/Applications/RoboFont3.app/Contents/Resources/lib/python3.6/vanilla/vanillaList.py", line 53, in observeValueForKeyPath_ofObject_change_context_
    self._targetMethod()
  File "/Applications/RoboFont3.app/Contents/Resources/lib/python3.6/vanilla/vanillaList.py", line 787, in _edit
    self._editCallback(self)
  File "scaleFast.py", line 987, in _editMasterFontsList
  File "/Users/ford/Library/Application Support/RoboFont/plugins/ScaleFast.roboFontExt/lib/mutatorScale/lib/mutatorScale/objects/scaler.py", line 187, in addMaster
    self.update()
  File "/Users/ford/Library/Application Support/RoboFont/plugins/ScaleFast.roboFontExt/lib/mutatorScale/lib/mutatorScale/objects/scaler.py", line 152, in update
    self._determineWorkingStems()
  File "/Users/ford/Library/Application Support/RoboFont/plugins/ScaleFast.roboFontExt/lib/mutatorScale/lib/mutatorScale/objects/scaler.py", line 367, in _determineWorkingStems
    twoAxes = self._checkForTwoAxes(stems)
  File "/Users/ford/Library/Application Support/RoboFont/plugins/ScaleFast.roboFontExt/lib/mutatorScale/lib/mutatorScale/objects/scaler.py", line 394, in _checkForTwoAxes
    return bool(reduce(lambda a,b: a*b, twoAxes))
NameError: name 'reduce' is not defined
```

Thankfully it seems like the fix is just moving `from functools import reduce` to the top of the file... I think the reason this wasn't caught before was because it was being imported for the automated tests, but not for the larger module.

**Comment by colinmford** [comment]
Pull request #3 fixes the issue for me.

**Comment by colinmford** [comment]
Or — this looks like this is an issue in mutatorScale... so maybe this should be fixed there.  But I can't file an issue in roboDocs/MutatorScale because it's a fork.

**Comment by gferreira** [comment]
you are right, this issue belongs to [MutatorScale](https://github.com/roboDocs/MutatorScale/), which is included in ScaleFast using `git subtree` – see the [discussion in the forum](https://forum.robofont.com/topic/606/scalefast-and-mutatorscale).

I’ll now try to push your changes to the MutatorScale repository, following the steps described in [Updating the Shared Library Remote with Changes made in the Subtree](https://www.codeproject.com/Articles/562949/ManagingplusNestedplusLibrariesplusUsingplustheplu#Update-REmote-From-Sub-Project).

issues in roboDocs/MutatorScale are now allowed, thanks for mentioning it.

**Comment by gferreira** [comment]
✔︎ [done](http://github.com/roboDocs/MutatorScale/pull/1)
