### ISSUE TITLE
mutatorMath typeError on 1.0.3 and RF 3.4

### ISSUE THREAD

**Issue by rbmntjs** [roboDocs/ScaleFast#9]
I’m getting a range of issues using the Mechanic version of ScaleFast and the latest RoboFont. No visuals, a long traceback, and, interestingly, typing in the character preview input doubles every character, but no preview shows. The traceback explains why, but I don’t understand the why :)

---

```
Traceback (most recent call last):
  File "/Users/robin/Code/RF-scripts/Robofont-3/Extensions/ScaleFast.roboFontExt/lib/mutatorScale/lib/mutatorScale/objects/scaler.py", line 295, in _getInstance
    b, m = buildMutator(masters)
  File "/Applications/RoboFont_alts/3.4/RoboFont.app/Contents/Resources/lib/python3.7/mutatorMath/objects/mutator.py", line 38, in buildMutator
    items = sorted(items)
TypeError: '<' not supported between instances of 'MathGlyph' and 'MathGlyph'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/RoboFont_alts/3.4/RoboFont.app/Contents/Resources/lib/python3.7/vanilla/vanillaEditText.py", line 11, in controlTextDidChange_
    self.action_(notification.object())
  File "/Applications/RoboFont_alts/3.4/RoboFont.app/Contents/Resources/lib/python3.7/vanilla/vanillaBase.py", line 503, in action_
    self.callback(sender)
  File "scaleFast.py", line 715, in _inputGlyphs
  File "scaleFast.py", line 1209, in _updatePreview
  File "scaleFast.py", line 756, in _buildScaledGlyphs
  File "scaleFast.py", line 763, in _retrieveScaledGlyph
  File "/Users/robin/Code/RF-scripts/Robofont-3/Extensions/ScaleFast.roboFontExt/lib/mutatorScale/lib/mutatorScale/objects/scaler.py", line 262, in getScaledGlyph
    instanceGlyph = self._getInstanceGlyph(targetLocation, mutatorMasters)
  File "/Users/robin/Code/RF-scripts/Robofont-3/Extensions/ScaleFast.roboFontExt/lib/mutatorScale/lib/mutatorScale/objects/scaler.py", line 286, in _getInstanceGlyph
    I = self._getInstance(location, masters)
  File "/Users/robin/Code/RF-scripts/Robofont-3/Extensions/ScaleFast.roboFontExt/lib/mutatorScale/lib/mutatorScale/objects/scaler.py", line 300, in _getInstance
    self.mutatorErrors.append({'error':e.message})
AttributeError: 'TypeError' object has no attribute 'message'
Traceback (most recent call last):
  File "/Users/robin/Code/RF-scripts/Robofont-3/Extensions/ScaleFast.roboFontExt/lib/mutatorScale/lib/mutatorScale/objects/scaler.py", line 295, in _getInstance
    b, m = buildMutator(masters)
  File "/Applications/RoboFont_alts/3.4/RoboFont.app/Contents/Resources/lib/python3.7/mutatorMath/objects/mutator.py", line 38, in buildMutator
    items = sorted(items)
TypeError: '<' not supported between instances of 'MathGlyph' and 'MathGlyph'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/RoboFont_alts/3.4/RoboFont.app/Contents/Resources/lib/python3.7/vanilla/vanillaEditText.py", line 11, in controlTextDidChange_
    self.action_(notification.object())
  File "/Applications/RoboFont_alts/3.4/RoboFont.app/Contents/Resources/lib/python3.7/vanilla/vanillaBase.py", line 503, in action_
    self.callback(sender)
  File "scaleFast.py", line 715, in _inputGlyphs
  File "scaleFast.py", line 1209, in _updatePreview
  File "scaleFast.py", line 756, in _buildScaledGlyphs
  File "scaleFast.py", line 763, in _retrieveScaledGlyph
  File "/Users/robin/Code/RF-scripts/Robofont-3/Extensions/ScaleFast.roboFontExt/lib/mutatorScale/lib/mutatorScale/objects/scaler.py", line 262, in getScaledGlyph
    instanceGlyph = self._getInstanceGlyph(targetLocation, mutatorMasters)
  File "/Users/robin/Code/RF-scripts/Robofont-3/Extensions/ScaleFast.roboFontExt/lib/mutatorScale/lib/mutatorScale/objects/scaler.py", line 286, in _getInstanceGlyph
    I = self._getInstance(location, masters)
  File "/Users/robin/Code/RF-scripts/Robofont-3/Extensions/ScaleFast.roboFontExt/lib/mutatorScale/lib/mutatorScale/objects/scaler.py", line 300, in _getInstance
    self.mutatorErrors.append({'error':e.message})
AttributeError: 'TypeError' object has no attribute 'message'
Traceback (most recent call last):
  File "/Users/robin/Code/RF-scripts/Robofont-3/Extensions/ScaleFast.roboFontExt/lib/mutatorScale/lib/mutatorScale/objects/scaler.py", line 295, in _getInstance
    b, m = buildMutator(masters)
  File "/Applications/RoboFont_alts/3.4/RoboFont.app/Contents/Resources/lib/python3.7/mutatorMath/objects/mutator.py", line 38, in buildMutator
    items = sorted(items)
TypeError: '<' not supported between instances of 'MathGlyph' and 'MathGlyph'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lib/doodleDelegate.pyc", line 96, in sendEvent_
  File "/Applications/RoboFont_alts/3.4/RoboFont.app/Contents/Resources/lib/python3.7/vanilla/vanillaEditText.py", line 11, in controlTextDidChange_
    self.action_(notification.object())
  File "/Applications/RoboFont_alts/3.4/RoboFont.app/Contents/Resources/lib/python3.7/vanilla/vanillaBase.py", line 503, in action_
    self.callback(sender)
  File "scaleFast.py", line 715, in _inputGlyphs
  File "scaleFast.py", line 1209, in _updatePreview
  File "scaleFast.py", line 756, in _buildScaledGlyphs
  File "scaleFast.py", line 763, in _retrieveScaledGlyph
  File "/Users/robin/Code/RF-scripts/Robofont-3/Extensions/ScaleFast.roboFontExt/lib/mutatorScale/lib/mutatorScale/objects/scaler.py", line 262, in getScaledGlyph
    instanceGlyph = self._getInstanceGlyph(targetLocation, mutatorMasters)
  File "/Users/robin/Code/RF-scripts/Robofont-3/Extensions/ScaleFast.roboFontExt/lib/mutatorScale/lib/mutatorScale/objects/scaler.py", line 286, in _getInstanceGlyph
    I = self._getInstance(location, masters)
  File "/Users/robin/Code/RF-scripts/Robofont-3/Extensions/ScaleFast.roboFontExt/lib/mutatorScale/lib/mutatorScale/objects/scaler.py", line 300, in _getInstance
    self.mutatorErrors.append({'error':e.message})
AttributeError: 'TypeError' object has no attribute 'message'
```

**Comment by rbmntjs** [comment]
I’ve found the problem, I think: when two masters have the same vstem/hstem, ScaleFast tries to place both masters on the same position, and that doesn’t work. But the advance widths are dramatically different (60% narrower in the narrow style), so it does feel surprising that it doesn’t work.
